addSbtPlugin("com.eed3si9n"       % "sbt-buildinfo"         % "0.3.2")
addSbtPlugin("de.heikoseeberger"  % "sbt-header"            % "1.4.0")
addSbtPlugin("com.typesafe.sbt"   % "sbt-pgp"               % "0.8.3")
addSbtPlugin("com.github.gseitz"  % "sbt-release"           % "0.8.5")
addSbtPlugin("org.scalastyle"    %% "scalastyle-sbt-plugin" % "0.6.0")
addSbtPlugin("org.xerial.sbt"     % "sbt-sonatype"          % "0.2.1")
